queue_rules:
  - name: default
    merge_method: squash
    queue_conditions: []
    merge_conditions: []

pull_request_rules:
  - name: auto-queue on ready-to-merge label
    conditions:
      - base=main
      - label=ready-to-merge
    actions:
      queue:
        name: default
