queue_rules:
  - name: default
    merge_method: squash
    allow_inplace_checks: false
    batch_size: 1
    queue_conditions: []
    merge_conditions:
      - "#approved-reviews-by>=1"
      - check-success=integration-gate

pull_request_rules:
  - name: queue on approval+label
    conditions:
      - base=main
      - label=ready-to-merge
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
